export const growModelArticle = {
  meta: {
    label: 'Coaching conversation guide',
    readingTime: '约 14 分钟阅读',
  },
  contents: [
    { href: '#grow-overview', label: '起源与用途' },
    { href: '#grow-framework', label: '四阶段路径' },
    { href: '#grow-questions', label: '高质量问题库' },
    { href: '#grow-dialogue', label: '教练对话示例' },
    { href: '#grow-session', label: '一次会话流程' },
    { href: '#grow-practice', label: '场景与自我教练' },
    { href: '#grow-guardrails', label: '限制与常见错误' },
    { href: '#grow-action', label: '行动承诺与复盘' },
  ],
  overview: {
    title: 'GROW 不是四步问卷，而是一条由当事人主导的思考路径',
    paragraphs: [
      'GROW 在 20 世纪 80 年代的绩效教练实践中形成，由 John Whitmore 爵士及其在 Performance Consultants International 的同事发展并推广。名称来自 Goal、Reality、Options 与 Will / Way Forward，分别对应目标、现实、选择和行动意愿。',
      '它适用于需要澄清目标、理解障碍、作出选择并落实行动的对话。教练不负责替对方解题，而是通过开放问题、倾听、复述和适度挑战，让当事人看见自己的证据、资源与决定。',
    ],
    principleTitle: '判断一场 GROW 对话是否有效',
    principle: '不是看四组问题是否全部问完，而是看当事人能否说清自己要什么、现实是什么、有哪些可选路径，以及下一步愿意承担什么。',
    workingAgreement: [
      '先说明时间、主题和双方角色。',
      '区分可商量空间与不可协商边界。',
      '让当事人拥有目标、选项和承诺。',
    ],
  },
  stages: [
    {
      id: 'goal',
      letter: 'G',
      english: 'Goal',
      chinese: '目标',
      headline: '先定义值得抵达的结果',
      purpose: '澄清本次谈话、当前任务或更长期发展真正要实现什么，并确认目标对当事人的意义与可控范围。',
      output: '产出：一条有期限、有成功信号、由当事人认领的目标陈述。',
      questions: [
        '今天这段对话结束时，你最希望带走什么结果？',
        '这件事为什么现在重要，它与你重视的什么有关？',
        '如果目标实现，别人会观察到哪些具体变化？',
        '其中哪些结果由你直接控制，哪些只能影响？',
        '需要把目标限定在什么范围和时间内？',
        '如果理想结果是 10 分，10 分的画面具体是什么？',
      ],
    },
    {
      id: 'reality',
      letter: 'R',
      english: 'Reality',
      chinese: '现实',
      headline: '用事实看清当前起点',
      purpose: '探索已经发生的事实、当前行为与结果、正在发挥作用的资源，以及阻碍进展的模式、约束和假设。',
      output: '产出：目标与现状之间的关键差距，以及仍需验证的信息。',
      questions: [
        '目前实际发生了什么，哪些是事实，哪些是你的解释？',
        '什么已经在起作用，你用什么证据判断？',
        '你尝试过哪些做法，各自产生了什么结果？',
        '最大的障碍是什么，它背后是否存在重复模式？',
        '谁会影响结果，他们现在如何看待这件事？',
        '还缺少哪条信息，得到它后可能改变你的判断？',
      ],
    },
    {
      id: 'options',
      letter: 'O',
      english: 'Options',
      chinese: '选择',
      headline: '先扩展可能，再评估取舍',
      purpose: '在过早评价或给建议之前，产生足够多的路径，并比较每条路径的价值、成本、风险与所需支持。',
      output: '产出：至少三个真实可选方案，以及清楚的取舍依据。',
      questions: [
        '先不判断可行性，你还能想到哪些做法？',
        '如果资源限制暂时消失，你会尝试什么？',
        '你有哪些优势、经验或关系可以借用？',
        '如果同事带着同样问题来找你，你会建议什么？',
        '哪个最小实验能用较低成本验证关键假设？',
        '这些选项能否组合，每一种需要放弃什么？',
      ],
    },
    {
      id: 'will',
      letter: 'W',
      english: 'Will / Way Forward',
      chinese: '行动意愿',
      headline: '把选择变成可复盘的承诺',
      purpose: '由当事人选择准备执行的路径，明确下一步、时间、完成证据、障碍预案、支持关系与复盘节点。',
      output: '产出：一个能在 24 小时内启动，并有人跟进的行动计划。',
      questions: [
        '你决定采用哪条路径，为什么是它？',
        '第一步具体是什么，你会在何时、何地完成？',
        '什么证据能够说明这一步真的完成了？',
        '最可能让你停下来的因素是什么，你准备如何应对？',
        '从 1 到 10，你的承诺度是多少；低于 8 分要怎样调整？',
        '谁需要知情或提供支持，何时一起复盘？',
      ],
    },
  ],
  loopback: {
    title: '允许往返，才能保持真实',
    description: 'GROW 提供方向，但不要求机械线性。目标与现实通常值得投入更多时间；新事实、低承诺或不可控目标出现时，应回到前一阶段重新校准。',
    routes: [
      { from: 'Reality', to: 'Goal', when: '现实信息表明原目标过宽、不可控或并非真正需要解决的问题。' },
      { from: 'Options', to: 'Reality', when: '所有方案都依赖未经验证的假设，需要补充事实和利益相关方信息。' },
      { from: 'Will', to: 'Options', when: '承诺度低于 8 分，说明选项、范围或支持条件仍需调整。' },
    ],
  },
  dialogue: {
    title: '示例：从“项目不要再延期”走向可负责的行动',
    description: '场景：产品运营负责人林悦带领 8 人团队。近期 8 个里程碑中有 4 个延期，她认为跨部门响应慢是主要原因。',
    turns: [
      { stageId: 'goal', stage: 'G', speaker: '教练', text: '这次谈话结束时，你希望自己对什么更清楚？' },
      { stageId: 'goal', stage: 'G', speaker: '林悦', text: '我想让项目以后都不要延期。' },
      { stageId: 'reality', stage: 'R', speaker: '教练', text: '回看最近四次延期，分别发生了什么？哪些因素在你的控制内？' },
      { stageId: 'reality', stage: 'R', speaker: '林悦', text: '两个依赖其他团队，一个需求中途改变，还有一个是我们到周五才暴露风险。外部响应我不能决定，但风险通常发现得太晚。' },
      { stageId: 'goal', stage: 'G', speaker: '教练', text: '如果把不可控部分拿掉，四周后你愿意为哪个结果负责？', loopback: '回到 Goal：把愿望改写为可控目标' },
      { stageId: 'goal', stage: 'G', speaker: '林悦', text: '连续四周在周一确认风险，关键依赖在 24 小时内升级，让 8 个里程碑中延期的不超过 2 个。' },
      { stageId: 'options', stage: 'O', speaker: '教练', text: '先不评价，列出至少三种能更早暴露风险的办法。' },
      { stageId: 'options', stage: 'O', speaker: '林悦', text: '建立一页风险板；周二、周四做 15 分钟依赖检查；每个外部依赖指定一名内部责任人；重大需求变更先评估里程碑影响。' },
      { stageId: 'will', stage: 'W', speaker: '教练', text: '你选择什么？第一步何时发生？什么最可能阻碍你？' },
      { stageId: 'will', stage: 'W', speaker: '林悦', text: '今天 17:00 前发出风险板，明天首次检查。我担心会议变长，所以限制为 15 分钟，只处理红色依赖。承诺度 8 分，下周五和你复盘。' },
    ],
    takeaways: [
      '目标从无法完全控制的“零延期”，收窄为可观察、可负责的领先行为与结果。',
      '教练没有给出工具答案，而是让林悦先生成并选择方案。',
      '行动包含开始时间、范围边界、障碍预案、承诺度和复盘日期。',
    ],
  },
  session: {
    title: '一次 50 分钟会话的实际节奏',
    description: '时间只是一种参考。话题复杂时，可以把一次会话用于 Goal 与 Reality，把 Options 和 Will 留到下一次；清晰度比赶完流程更重要。',
    steps: [
      { time: '0-5 分钟', title: '约定主题与边界', detail: '确认今天处理什么、可用时间、保密边界，以及经理此刻是在教练、提供信息还是作管理决定。', output: '共同议程' },
      { time: '5-15 分钟', title: '澄清 Goal', detail: '定义本次谈话和更长期目标，检查重要性、可控性、成功信号与时间范围。', output: '目标陈述' },
      { time: '15-27 分钟', title: '探索 Reality', detail: '区分事实与解释，回顾尝试、资源、障碍、相关方和假设。必要时返回 Goal 收窄目标。', output: '关键差距' },
      { time: '27-38 分钟', title: '生成 Options', detail: '先扩展至少三个选择，再比较影响、成本、风险、支持条件和最小实验。', output: '选项与取舍' },
      { time: '38-47 分钟', title: '形成 Will', detail: '由当事人选择行动，写清第一步、时间、证据、障碍预案、支持者和承诺度。', output: '行动承诺' },
      { time: '47-50 分钟', title: '总结与约定复盘', detail: '请当事人亲自总结洞察和下一步，确认双方责任、记录方式与下一次检查日期。', output: '复盘节点' },
    ],
  },
  applications: {
    title: '哪些场景适合使用 GROW',
    items: [
      { title: '一对一发展对话', detail: '员工需要澄清能力目标、职业方向或下一阶段挑战，并愿意拥有自己的选择。' },
      { title: '绩效改进与问题解决', detail: '结果标准已明确，但实现路径仍有空间，需要从事实差距走向自主行动。' },
      { title: '项目受阻与重要决策', detail: '团队容易停留在单一解释，希望扩大选项并验证关键假设。' },
      { title: '团队教练', detail: '成员需要形成共同目标、共享现实、可比较方案和清晰责任。' },
      { title: '个人习惯与学习目标', detail: '个人希望把模糊愿望转化为能启动、能观察、能复盘的小步行动。' },
    ],
  },
  selfCoaching: {
    title: '没有教练时，用一页纸完成自我教练',
    description: '给自己 15 分钟，按顺序书写而不是只在脑中回答。每一栏最多保留三条关键内容。',
    steps: [
      { label: '01', title: '写下结果', detail: '用一句话说明期限、成功信号和自己能够控制的部分。' },
      { label: '02', title: '列事实与解释', detail: '左右分栏，避免把担忧、推测或自我评价当成事实。' },
      { label: '03', title: '强制生成三个选项', detail: '其中至少一个是 48 小时内可验证的低成本实验。' },
      { label: '04', title: '选择并检查承诺', detail: '低于 8 分就缩小行动、换选项或补充支持，不用意志力掩盖阻力。' },
      { label: '05', title: '预约复盘', detail: '把检查时间写入日历，用新结果更新 Reality，再决定下一轮行动。' },
    ],
  },
  guardrails: {
    title: '知道边界，才能避免把结构用成套路',
    limitations: [
      { title: '它不是心理治疗或危机干预', detail: '当话题涉及创伤、严重心理困扰、安全风险或医疗问题时，应转介合格专业人员。' },
      { title: '它不能消除权力关系', detail: '经理兼任教练时，员工可能不会完全坦诚。应明确评价边界、信息用途和真正可选择的空间。' },
      { title: '个人行动不能替代系统修复', detail: '资源不足、角色冲突、歧视或不合理制度等问题，需要组织层面的决定，不能只要求个人调整。' },
      { title: '简单结构可能压缩复杂议题', detail: '长期身份、价值冲突或多方博弈通常需要多次会话和其他分析工具，不宜强行在一次谈话内闭环。' },
    ],
    mistakes: [
      { title: '目标是经理的，不是当事人的', correction: '先说明业务边界，再邀请当事人定义自己愿意负责的结果与路径。' },
      { title: '尚未理解现实就急着给方案', correction: '追问事实、既往尝试与模式，把建议延后到共同理解差距之后。' },
      { title: '用诱导问题包装既定答案', correction: '提出真正开放的问题；需要建议时明确征得同意，并说明自己正在切换角色。' },
      { title: '机械按顺序问完四组问题', correction: '跟随对话信息往返，尤其在目标不可控、事实不足或承诺偏低时回到前一阶段。' },
      { title: '行动很多，却没有优先级', correction: '只保留最能推进目标的第一步，并写清时间、完成证据和障碍预案。' },
      { title: '结束时没有复盘安排', correction: '把复盘日期和责任人写进计划，让行动结果成为下一轮 Reality。' },
    ],
  },
  actionPlan: {
    title: '把 Will 写成可以检查的行动计划',
    description: '以下继续使用林悦的案例。计划不追求事项多，而是让每项行动都有启动时间、完成证据、障碍预案和复盘责任。',
    goal: '四周内，每周一完成风险确认，关键依赖在 24 小时内升级；8 个里程碑中延期不超过 2 个。',
    rows: [
      { action: '发布一页风险板，并标记红色依赖', timing: '今天 17:00 前', evidence: '团队频道中可访问的首版风险板', contingency: '信息不全时先发布最小版本，缺口明确标注负责人', accountability: '林悦负责；教练次日查看' },
      { action: '进行周二、周四依赖检查', timing: '每次 15 分钟', evidence: '红色依赖均有责任人和下一节点', contingency: '议题超时则转为会后双边处理，不扩大会程', accountability: '项目负责人轮值；周五汇总' },
      { action: '对重大需求变更评估里程碑影响', timing: '变更提出后 24 小时内', evidence: '变更记录包含范围、时间与责任调整', contingency: '无法判断时升级产品负责人和交付负责人共同决策', accountability: '林悦跟进；下周五复盘' },
    ],
    commitment: {
      score: '8 / 10',
      label: '当前承诺度',
      note: '若执行前降到 8 分以下，先缩小动作或补齐支持条件，而不是继续追加要求。',
    },
    reviewQuestions: [
      '哪些行动按约完成，证据是什么？',
      '结果与原先假设有哪些不同？',
      '哪些障碍可由个人处理，哪些需要组织支持？',
      '目标、选项或下一步需要怎样更新？',
    ],
  },
  sources: [
    {
      title: 'What Is the GROW Coaching Model? (Incl. Examples)',
      url: 'https://positivepsychology.com/grow-coaching-model/',
      checkedAt: '2026-08-11',
      usedFor: '核实模型起源、四阶段含义、非线性使用方式、开放问题方法、应用场景和行动问责。正文已用中文重新归纳并结合管理场景改写。',
    },
  ],
} as const;
